name: create-debug

on:
  workflow_dispatch:  # Enables manual trigger

env:
  ANDROID_PROJECT_DIR: Andorid

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: make gradlew executable
      run: chmod +x gradlew

    - name: Assemble Debug
      run: ./gradlew assembleDebug

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: ${{ env.ANDROID_PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk


